MystenLabs/sui-rust-sdk

src/types/transaction/mod.rs

Make some of the commands types' fields public. It's probably safe to do so as these commands are used to build up transactions.

Make some of the commands types' fields public

---

crates/sui-graphql-client/src/lib.rs

This simply tests that it can connect to a network and run and get back a request successfully, without any failures. This can catch if something changes in the GraphQL url, schema, BCS issues, etc.

[GraphQL Client] Add tests

---

crates/sui-graphql-client/src/lib.rs
crates/sui-graphql-client/src/query_types/events.rs

GraphQL sets the sender to None if the event's sender is address 0x0. We make it back into 0x0 here to avoid making sender an optional field on Event.

Fix events by making sender to 0x0 if it's null from the GQL query

---

.github/workflows/ci.yml
Makefile
crates/sui-crypto/src/simple.rs
crates/sui-crypto/src/zklogin/mod.rs
crates/sui-crypto/src/zklogin/poseidon/mod.rs
crates/sui-crypto/src/zklogin/verify.rs
crates/sui-graphql-client/examples/custom_query.rs
crates/sui-graphql-client/src/faucet.rs
crates/sui-graphql-client/src/lib.rs
crates/sui-graphql-client/src/query_types/active_validators.rs
crates/sui-graphql-client/src/query_types/balance.rs
crates/sui-graphql-client/src/query_types/checkpoint.rs
crates/sui-graphql-client/src/query_types/coin.rs
crates/sui-graphql-client/src/query_types/epoch.rs
crates/sui-graphql-client/src/query_types/events.rs
crates/sui-graphql-client/src/query_types/execute_tx.rs
crates/sui-graphql-client/src/query_types/mod.rs
crates/sui-graphql-client/src/query_types/object.rs
crates/sui-graphql-client/src/query_types/transaction.rs
crates/sui-sdk-types/src/hash.rs
crates/sui-sdk-types/src/types/crypto/passkey.rs
crates/sui-sdk-types/src/types/transaction/serialization.rs

In an effort to reduce merge conflicts, run rustfmt with 'imports_granularity=Item' to have each imported item be on a separate line.

chore: format with imports_granularity=Item

---

crates/sui-graphql-client/src/lib.rs
crates/sui-graphql-client/src/query_types/transaction.rs

The `TransactionBlock` bcs in GraphQL now encodes the `TransactionData`. This PR fixes the logic to correctly deserialize the transaction bcs data and signatures into a `SignedTransaction`. 
As the service does not serve yet the new data, I tested it locally by starting a local network and GraphQL server. For now, I put an `#ignore` on the test.

Fix transaction(s) query

---

crates/sui-graphql-client/schema/graphql_rpc.graphql
crates/sui-graphql-client/src/lib.rs
crates/sui-graphql-client/src/query_types/events.rs
crates/sui-graphql-client/src/query_types/transaction.rs

This PR updates to the latest GraphQL schema that was merged just today. The new schema added events' BCS and added packageBCS, among other things.
As this is not deployed yet on any network, I tried it with a local network and an example. 
```
let client = Client::new_localhost();
let events = client
.events(None, None, None, None, Some(10))
.await
.unwrap();
```
```
sui-rust-sdk/target/debug/examples/events`
Event { package_id: ObjectId(Address("0x0000000000000000000000000000000000000000000000000000000000000003")), module: Identifier("sui_system"), sender: Address("0x0000000000000000000000000000000000000000000000000000000000000000"), type_: StructTag { address: Address("0x0000000000000000000000000000000000000000000000000000000000000003"), module: Identifier("validator"), name: …
```

Use the new GraphQL schema + fix events to use the new bcs field

---

crates/sui-graphql-client/src/lib.rs
crates/sui-graphql-client/src/query_types/mod.rs

This PR simplifies the return type of several APIs from `Result<Option<Page>, Error>` to `Result<Page, Error>`. 
The Page type has now a `is_empty` function to check if there is no information returned in this page.
It should simplify a bit working with the results of these APIs.

[GraphQL Client] Rework the Page type and APIs that return Option<Page> 

---

crates/sui-graphql-client/src/lib.rs
crates/sui-graphql-client/src/query_types/active_validators.rs
crates/sui-graphql-client/src/query_types/events.rs

This PR adds a pagination filter instead of explicitly requiring after/before/first/last, which was quite wrong. A user cannot pass a cursor randomly, it needs to come from a page information that was returned by GraphQL.

[GraphQL Client] Add a pagination filter

---

.github/workflows/ci.yml
Makefile
crates/sui-graphql-client/README.md
crates/sui-graphql-client/src/lib.rs

This updates the CI to enable a local network to be run from a testnet sui binary. It also splits the makefile tests into two: one for those tests that do not require a network, and one for those that need, e.g., graphql-client and soon sui-transaction-builder.
Changed tests to run on a local network. That means that things can still break if the schema is updated without updating to the binary that contains the released schema, so if that happens often, we might want to add a check on that.

[CI+GraphQL] Download Sui binary for localnet running in the CI + have tests only run on localnet 

---

crates/sui-graphql-client/src/lib.rs
crates/sui-graphql-client/src/query_types/dynamic_fields.rs
crates/sui-graphql-client/src/query_types/mod.rs
crates/sui-graphql-client/src/query_types/object.rs

Added `dynamic_field`, `dynamic_object_field` and `dynamic_fields` queries to client. They all return a type that includes the `serde_json::Value` and `Object`. Also added a `dynamic_fields_on_wrapped_objects` function that uses the `owner` to query for dynamic fields. 
My understanding from the GraphQL code is that `MoveObject`'s bcs is the more generic `Object`, which should work just fine.
Finally, the last few changes ([3be26a8b](https://github.com/MystenLabs/sui-rust-sdk/pull/18/commits/3be26a8bf8c7cbe524e09b2c1299cd5965b68b11) and [43fbd400](https://github.com/MystenLabs/sui-rust-sdk/pull/18/commits/43fbd40058f980c6b811df82f276b76ec143957b)) were informed by integrating this `sui-sdk-types` and `sui-graphql-client` as dependencies in another project. The CLI there relies heavily on …

Add dynamic fields query

---

crates/sui-graphql-client/src/lib.rs
crates/sui-graphql-client/src/query_types/dynamic_fields.rs

Forgot to decode bcs from base64 for dynamic fields. This also changes to using `Typetag` for the return type in DynamicFieldOutput, to ensure consistency all around.

[GraphQL][DF] Fix return of bcs and typetag in DynamicFieldOutput

---

crates/sui-graphql-client/src/lib.rs
crates/sui-graphql-client/src/query_types/dynamic_fields.rs

Align this function to have a similar return signature as all the other functions that return `Result<Page<T>>`.

[GraphQL Client][DFS] Return Result<Page> instead of Result<Option<Page>>

---

crates/sui-graphql-client/src/lib.rs
crates/sui-graphql-client/src/query_types/checkpoint.rs
crates/sui-graphql-client/src/query_types/mod.rs

This PR adds total transaction blocks queries that return the number of tx blocks up to the specified checkpoint. 
In addition, it fixes two issues on checkpoint digests
- moves the digest to be a Digest type
- checkpoint digests were not base58 decoded

[GraphQL Client] Add total transaction blocks query

---

crates/sui-graphql-client/src/lib.rs
crates/sui-graphql-client/src/query_types/dynamic_fields.rs

This PR fixes a bug with the way dynamic fields are fetched. If we use the owner instead of objects, we also get the DFs on wrapped objects IIUC.

[GraphQL Client] Fetch dynamic field via owner instead of object.

---

crates/sui-graphql-client/src/lib.rs

This PR achieves three things:
1. Moves packages related queries to return a `Page<T>` instead of `Option<Page<T>>`.
2. Adds tests back by removing the ignore
3. Expands the package related tests to ensure there's an actual package retrieved by the query.

[GraphQL Client] Cleanup of Option<Page> and add tests back

---

crates/sui-sdk-types/src/types/transaction/unresolved.rs

This `,` breaks the cargo fmt.

Fix issue with serde renaming

---

crates/sui-sdk-types/src/hash.rs
crates/sui-sdk-types/src/types/crypto/zklogin.rs
crates/sui-sdk-types/src/types/object.rs

[Latest CI run on another PR fails](https://github.com/MystenLabs/sui-rust-sdk/actions/runs/12173093096/job/33952882567?pr=41) so this PR should fix it.

[fix-ci][sdk-types] Fix as per clippy suggestions

---

crates/sui-graphql-client/src/lib.rs
crates/sui-graphql-client/src/query_types/events.rs
crates/sui-graphql-client/src/query_types/transaction.rs

This PR changes the return type for the `events` API to include the `TransactionDigest` corresponding to the transaction block that issued this event. 
@dario requested this change.

Return a tuple of Event, TxDigest

---

.github/workflows/ci.yml
crates/sui-graphql-client-build/schema.graphql

This PR updates:
- the GraphQL schema to the one in the branch `releases/sui-v1.39.0`
- the CI to use Sui CLI v1.39.1 to match the schema.

[GraphQL Client] Update schema

---

crates/sui-graphql-client/src/lib.rs
crates/sui-graphql-client/src/query_types/checkpoint.rs

Get checkpoint summary from bcs instead of manually converting it. This is dependent on first landing
https://github.com/MystenLabs/sui/pull/20340
Note: this will have to sit for a while because we have no releases in the upcoming weeks so we cannot get an updated version of the CLI that includes the latest schema changes.

[GraphQL Client] Use `bcs` from `Checkpoint` instead of manual conversion.

---

crates/sui-graphql-client/src/lib.rs
crates/sui-transaction-builder/src/lib.rs

Fix the digests to use the correct types.

[GraphQL Client] Fix digests

---

crates/sui-graphql-client/Cargo.toml

Force reqwest to use rustls-tls to avoid using openssl via native-tls crate.

[GraphQL Client] Force reqwest to use rustls-tls to avoid using openssl

---

crates/sui-crypto/Cargo.toml
crates/sui-sdk-types/Cargo.toml
crates/sui-sdk-types/Makefile

Update proptest to 1.6.0 which addresses the various bugs that were causing us to pin to a patched version.

chore: update proptest to 1.6.0

---

Makefile

chore: add `help` target to Makefile to display the usage of all targets

---

crates/sui-sdk-types/src/object.rs

- 41a0604 **feat(sui-sdk-types): Object::as_struct getter**
- 9cc7fdd **feat(sui-sdk-types)!: remove `Object::has_public_transfer` getter**
Probably a good idea to keep `MoveStruct::has_public_transfer` private
to avoid any misinterpretation there (there's a comment clearly
stating it's deprecated)
Done as separate commits to make it easy to revert any change.
Closes #72

feat(sui-sdk-types)!: `Object` content getters

---

crates/sui-graphql-client/src/lib.rs
crates/sui-graphql-client/src/query_types/dynamic_fields.rs

This PR fixes a bug with fetching dynamic _**object**_  fields by changing `object` field in `DynamicObjectFieldQuery` query to `owner`.
I believe that change was already applied for regular DFs, but not object ones, here: #54

fix: use `owner` instead of `object` in gql `DynamicObjectFieldQuery`

---

.github/workflows/ci.yml
crates/sui-crypto/src/zklogin/mod.rs
crates/sui-graphql-client-build/schema.graphql
crates/sui-graphql-client/src/lib.rs
crates/sui-graphql-client/src/query_types/object.rs

This PR updates the GraphQL schema to the one in v1.44.2, as the `objectKeys` of `ObjectFilter` type has been dropped in favor of a `multiGetObjects` top-level query.

[GraphQL] Update GraphQL schema and make appropriate changes on ObjectFilter

---

crates/sui-sdk-types/src/transaction/mod.rs
crates/sui-sdk-types/src/transaction/serialization.rs

This variant is missing in the latest release of `sui-sdk-types`. This time I didn't find it in `master`.
The implementation here is not polished like the rest of the library. See the two TODOs I added. If you want, you can take it over from here, but I'm happy to finish the job if given the right instructions.
IMO, it would be fine to leave the `StoredExecutionTimeObservations` inner type private for now if that means we can get it out faster.
In terms testing, I'm using this branch to patch our `sui-sdk-types` dependency that's used in our testnet ingestion pipelines and everything is working well so far :)

Hotfix: missing `EndOfEpochTransactionKind::StoreExecutionTimeObservations`

---

crates/sui-sdk-types/src/object.rs
crates/sui-transaction-builder/src/lib.rs
crates/sui-transaction-builder/src/unresolved.rs

This adds support for the new ConsensusAddress Owner variant which indicates that a single address has exclusive ownership of an object, but that the object is used as a "shared" input to transactions and version managmenet is handled by consensus similar to how this is done for shared objects.

owner: add support for ConsensusAddress Owner variant

---

crates/sui-sdk-types/src/execution_status.rs

`InvalidLinkage` is a new `ExecutionStatus` that is added in https://github.com/MystenLabs/sui/pull/22321/files, so adding it here and will then pull this over into `main` and then rebase that PR onto it before landing.
Note that this status will not be present (in terms of actually being possible to be returned) until the new adapter is enabled.

[execution status] Add new execution status

---

crates/sui-graphql-client/queries/coin_metadata.graphql
crates/sui-graphql-client/src/query_types/coin.rs

Added `address` to `CoinMetadata` type returned in `CoinMetadataQuery` used in Client.coin_metadata. Returning the id of the CoinMetadata object is essential from my perspective.

sui-graphql-client: return address for CoinMetadata query

---

crates/sui-crypto/Cargo.toml
crates/sui-crypto/Makefile
crates/sui-crypto/src/bls12381.rs
crates/sui-crypto/src/lib.rs
crates/sui-crypto/src/multisig.rs
crates/sui-sdk-types/src/hash.rs

Introduce bls12381 support, adding the ability to sign, aggregate and verify validator signatures over CheckpointSummary messages.

sui-crypto: introduce bls12381 support

---

crates/sui-rpc/src/client/mod.rs
crates/sui-rpc/src/client/staking_rewards.rs

Unlike in the old JSONRPC api, the new gRPC api does not have an api for fetching/calculating staking rewards. Instead its expected that clients call the "0x3::sui_system::calculate_rewards" move function (via a SimulateTransaction call) to determine the quantity of rewards that have been accrued by a staking delegation.
In order to assist with that, this patch introduces `Client::list_delegated_stake` and `Client::get_delegated_stake` methods to handle this for listing information about all delegations or getting information about a single delegation respectively.

sui-rpc: add helper for fetching staking information

---

crates/sui-rpc/src/client/v2/mod.rs
crates/sui-rpc/src/client/v2/transaction_execution.rs

Propagating all of the context necessary to debug transaction execution errors

refactor to better capture error info
